all:
  hosts:
    master:
      ansible_host: 84.252.133.212
      ip: 192.168.10.100 
      ansible_user: ubuntu
      kubeconfig_localhost: true
    worker1:
      ansible_host: 130.193.38.67
      ip: 192.168.100.34
      ansible_user: ubuntu
    worker2:
      ansible_host: 158.160.69.16
      ip: 192.168.200.20
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
        worker1:
        worker2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}