apiVersion: v1
kind: Service
metadata:
  name: nmynginx
  labels:
    app: nmynginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
  selector:
    app: nmynginx
