apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmynginx
  labels:
    app: nmynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nmynginx
  template:
    metadata:
      labels:
        app: nmynginx
    spec:
      containers:
        - name: nmynginx
          image: caevert24/nmynginx
          ports:
            - containerPort: 80
